### ISSUE TITLE
Keras 1.0 - Cannot import MaskedLayer

### ISSUE THREAD

**Issue by ohadle** [farizrahman4u/seq2seq#62]
In Keras 1.0 there was an API change in keras.layers.core, and import of SimpleSeq2seq fails:
```
In [5]: from seq2seq.models import SimpleSeq2seq
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-4a318390fc13> in <module>()
----> 1 from seq2seq.models import SimpleSeq2seq

/home/ohad/anaconda2/lib/python2.7/site-packages/seq2seq/models.py in <module>()
      5 from seq2seq.layers.encoders import LSTMEncoder
      6 from seq2seq.layers.decoders import LSTMDecoder, LSTMDecoder2, AttentionDecoder
----> 7 from seq2seq.layers.bidirectional import Bidirectional
      8 from keras.layers.recurrent import LSTM
      9 from keras.layers.core import RepeatVector, Dense, TimeDistributedDense, Dropout, Activation

/home/ohad/anaconda2/lib/python2.7/site-packages/seq2seq/layers/bidirectional.py in <module>()
      1 from __future__ import division
      2 from keras import backend as K
----> 3 from keras.layers.core import MaskedLayer
      4 try:
      5     import cPickle as pickle

ImportError: cannot import name MaskedLayer
```

**Comment by htw2012** [comment]
I also met the problem.Maybe Seq2seq did not support keras 1.0.

**Comment by iamyuanchung** [comment]
I met the same problem. Does anyone know how to fix it?

**Comment by ohadle** [comment]
For my `SimpleSeq2seq` needs I used an ugly hacky workaround:
```
import keras
keras.layers.core.MaskedLayer = object
from seq2seq.models import SimpleSeq2seq, Seq2seq, Seq2seqBase
from keras.models import Sequential
Seq2seqBase.add = Sequential.add
```
Untested on anything else.

**Comment by DenXX** [comment]
I believe you can replace MaskedLayer with Marking

**Comment by farizrahman4u** [comment]
![good_news](https://cloud.githubusercontent.com/assets/11006006/16474898/12094284-3e98-11e6-8069-19a65ac1fd3d.jpg)

Pulled an all nighter.. Seq2seq now works with Keras 1.0

**Comment by farizrahman4u** [comment]
![good_news](https://cloud.githubusercontent.com/assets/11006006/16475414/05464dd6-3e9c-11e6-9e5c-10aaf5fe2bf4.jpg)


Pulled an all nighter. Seq2seq now works with Keras 1.0.
